apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-nginx-cluster-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx-role-biding
subjects:
- kind: ServiceAccount
  name: ingress-nginx 
  namespace: ingress-nginx
roleRef:
  kind: ClusterRole
  name: ingress-nginx-cluster-role
  apiGroup: rbac.authorization.k8s.io
