apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}       # this needs to be templated
  labels:
    kiamol: ch10-lab
spec:
  selector:
    matchLabels:            # this needs to be templated
      app: {{ .Release.Name }}        
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:               # this needs to be templated
        app: {{ .Release.Name }}
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: web
          image: kiamol/ch04-todo-list
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: {{ .Values.environment | camelcase }}     # this should be parameterized
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Values.configMap.name }}   # this needs to be templated
