apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}    # this needs to be templated
  labels:
    kiamol: ch10-lab
spec:
  ports:
    - port: {{ .Values.service.port }}         # this should be parameterized
      targetPort: 80
  selector:              # this needs to be templated
    app: {{ .Release.Name }}
    environment: {{ .Values.environment }}
  type: {{ .Values.service.type }}     # this should be parameterized