apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RestrictedPaths
metadata:
  name: restrictedpaths
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    labelSelector:
      matchExpressions:
        - key: kiamol
          values: ["ch16-lab"]
          operator: In
  parameters:
    paths: ["/", "/bin", "/etc"]
