apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-web-lab
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # storageClassName: csi-hostpath-sc
